version: '3.8'
services:
  mysql:
    image: 'mysql'
    restart: unless-stopped
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
  wordpress:
    image: 'wordpress'
    restart: unless-stopped
    env_file:
      - ./env/wordpress.env
    depends_on:
      - mysql
    ports:
      - '80:80'
    volumes:
      - wordpress:/var/www/html
volumes:
  data:
  wordpress: